### ISSUE TITLE
FTDIDevice TypeError

### ISSUE THREAD

**Issue by crockpotveggies** [thomaschaaf/node-ftdi#29]
Using node version 9.9.0. Appears to be some sort of incompatibility with a recent version of node:

```
/home/pi/Projects/ponic-pi/node_modules/ftdi/index.js:42
  this.FTDIDevice = new FTDIDevice(settings);
                    ^

TypeError: new expects a object as argument
    at new FtdiDevice (/home/pi/Projects/ponic-pi/node_modules/ftdi/index.js:42:21)
    at /home/pi/Projects/ponic-pi/server.js:4:16
```

**Comment by crockpotveggies** [comment]
This was a misleading error. The real cause was that a device could not be found. Closing...
