### ISSUE TITLE
Can not install on OSX 10.9.4 - "fatal error: 'ftd2xx.h' file not found"

### ISSUE THREAD

**Issue by mathiasschopmans** [thomaschaaf/node-ftdi#8]
Hi. I'd like to use the lib to control a usb2dmx - interface via node. 
I tried to install node-ftdi manually on my Retina Macbook running 10.9.4, but it fails. :(
- clone this repo
- `sudo ./install.sh`
- `sudo node-gyp rebuild`

Btw. the USB-DMX-Interface is working fine with QLC for Mac, so the driver should be installed correctly.

Any suggestions?

Here's the error-log

```
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.1
gyp info using node@0.10.30 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mathiasschopmans/Sites/node-ftdi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mathiasschopmans/.node-gyp/0.10.30/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/mathiasschopmans/.node-gyp/0.10.30',
gyp info spawn args   '-Dmodule_root_dir=/Users/mathiasschopmans/Sites/node-ftdi',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/ftdi/src/ftdi_device.o
In file included from ../src/ftdi_device.cc:11:
../src/ftdi_device.h:6:10: fatal error: 'ftd2xx.h' file not found
#include <ftd2xx.h>
         ^
1 error generated.
make: *** [Release/obj.target/ftdi/src/ftdi_device.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/mathiasschopmans/Sites/node-ftdi
gyp ERR! node -v v0.10.30
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
mMac:node-ftdi mathiasschopmans$ 
```

Thanks in advance!

**Comment by NPellet** [comment]
Still having some problems on 10.10

The install works fine on Mavericks but fails miserably on Yosemite.

- I ran the install.sh. -- Worked fine
- I've unloaded the driver with kextunload. -- Worked fine
- I removed the quarantine flag on the files. -- Worked fine
- I even set the 0777 chmod to all the files...

Any idea what I'm doing wrong ?

```Transientss-Mac-mini:test transients$ npm install ftdi
npm http GET https://registry.npmjs.org/ftdi
npm http 304 https://registry.npmjs.org/ftdi

> ftdi@1.1.0 preinstall /Users/transients/Transients/sourcecode/test/node_modules/ftdi
> node-gyp rebuild

  CXX(target) Release/obj.target/ftdi/src/ftdi_device.o
In file included from ../src/ftdi_device.cc:11:
../src/ftdi_device.h:6:10: fatal error: 'ftd2xx.h' file not found
#include <ftd2xx.h>
         ^
1 error generated.
make: *** [Release/obj.target/ftdi/src/ftdi_device.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/transients/.nvm/v0.10.26/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/transients/.nvm/v0.10.26/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/transients/Transients/sourcecode/test/node_modules/ftdi
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! ftdi@1.1.0 preinstall: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ftdi@1.1.0 preinstall script.
npm ERR! This is most likely a problem with the ftdi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ftdi
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.1.0
npm ERR! command "/Users/transients/.nvm/v0.10.26/bin/node" "/Users/transients/.nvm/v0.10.26/bin/npm" "install" "ftdi"
npm ERR! cwd /Users/transients/Transients/sourcecode/test
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path: 'npm-debug.log' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 14.1.0
npm ERR! command "/Users/transients/.nvm/v0.10.26/bin/node" "/Users/transients/.nvm/v0.10.26/bin/npm" "install" "ftdi"
npm ERR! cwd /Users/transients/Transients/sourcecode/test
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/transients/Transients/sourcecode/test/npm-debug.log
npm ERR! not ok code 0```

**Comment by polyclick** [comment]
any more updates on this?

**Comment by NPellet** [comment]
Somehow I did manage to fix it. My C library path was completely messed up by Python (I think, if I remember well). And hence the ftd2xx.h could not be found.

I can't recall how I fixed it, but I did fix it this way.

Just giving you a direction to look into.

**Comment by mmckegg** [comment]
@polyclick: try installing this fork https://github.com/mmckegg/node-ftdi

I had the same problem and fixed it by adding in more search paths in https://github.com/mmckegg/node-ftdi/blob/master/binding.gyp#L46

This PR #17 will be merged shortly.
